/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    parents: ParentAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    groups: Group;
    activities: Activity;
    announcements: Announcement;
    'closure-dates': ClosureDate;
    'faq-entries': FaqEntry;
    documents: Document;
    'staff-profiles': StaffProfile;
    'job-openings': JobOpening;
    'gallery-photos': GalleryPhoto;
    parents: Parent;
    'notification-log': NotificationLog;
    'kb-categories': KbCategory;
    'kb-articles': KbArticle;
    'email-campaigns': EmailCampaign;
    'question-log': QuestionLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'closure-dates': ClosureDatesSelect<false> | ClosureDatesSelect<true>;
    'faq-entries': FaqEntriesSelect<false> | FaqEntriesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'staff-profiles': StaffProfilesSelect<false> | StaffProfilesSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'gallery-photos': GalleryPhotosSelect<false> | GalleryPhotosSelect<true>;
    parents: ParentsSelect<false> | ParentsSelect<true>;
    'notification-log': NotificationLogSelect<false> | NotificationLogSelect<true>;
    'kb-categories': KbCategoriesSelect<false> | KbCategoriesSelect<true>;
    'kb-articles': KbArticlesSelect<false> | KbArticlesSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'question-log': QuestionLogSelect<false> | QuestionLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'life-page': LifePage;
    'admission-page': AdmissionPage;
    'careers-page': CareersPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'life-page': LifePageSelect<false> | LifePageSelect<true>;
    'admission-page': AdmissionPageSelect<false> | AdmissionPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Parent;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ParentAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authorized staff accounts. Parent (portal) accounts are managed separately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'director' | 'staff' | 'developer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Public site images. Never upload photos that could identify a child.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The CPE’s age groups. Children’s names must never appear here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  ageRange: string;
  /**
   * Chosen from the site palette — visual consistency is automatic.
   */
  color: 'miel' | 'sauge' | 'terracotta' | 'ciel' | 'lavande';
  order?: number | null;
  active?: boolean | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Group activities with preparation checklists. Private by default (parent portal); public only if you explicitly choose so. Never include personal information about a child.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  /**
   * Activities are private by default. Make an activity public only when you consciously choose to show it to everyone.
   */
  visibility: 'portal' | 'public';
  image?: (number | null) | Media;
  groups: (number | Group)[];
  date: string;
  endDate?: string | null;
  /**
   * Shown prominently: essential instructions for parents.
   */
  importantNote?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  checklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Announcements for parents. Never include personal information about a child.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  kind: 'news' | 'event' | 'reminder' | 'holiday';
  /**
   * Upcoming events are highlighted in the portal.
   */
  eventDate?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * Paste the video link (preferably unlisted). It is embedded in the portal.
   */
  videoUrl?: string | null;
  /**
   * Upload the PDF to Documents first, then attach it here.
   */
  attachments?: (number | Document)[] | null;
  scope: 'cpe' | 'groups';
  groups?: (number | Group)[] | null;
  pinned?: boolean | null;
  /**
   * Publish as usual: the announcement stays hidden from parents until this moment.
   */
  publishAt?: string | null;
  /**
   * Leaves the main feed but remains available in the portal archives.
   */
  archived?: boolean | null;
  /**
   * After this date the announcement is automatically filed under archives.
   */
  expiresAt?: string | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Downloadable documents: menus, policies, guides. No document may contain personal information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category: 'menus' | 'politiques' | 'guides' | 'general';
  audience: 'public' | 'portal';
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * CPE closure days (holidays, pedagogical days).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closure-dates".
 */
export interface ClosureDate {
  id: number;
  label: string;
  startDate: string;
  endDate?: string | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Official answers to parents’ questions. Only published content is visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-entries".
 */
export interface FaqEntry {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'admission' | 'quotidien' | 'sante' | 'alimentation' | 'general';
  audience: 'public' | 'portal';
  order?: number | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public team presentation. The person’s written consent is required before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-profiles".
 */
export interface StaffProfile {
  id: number;
  name: string;
  jobTitle: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  consent?: boolean | null;
  order?: number | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Positions shown on the public Careers page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  schedule: 'full' | 'part' | 'sub';
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images of past activities, publicly visible ONLY after confirming no child is identifiable and distribution is authorized.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos".
 */
export interface GalleryPhoto {
  id: number;
  caption: string;
  takenAt: string;
  activity?: (number | null) | Activity;
  consentConfirmed?: boolean | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Parent portal accounts, created by the administration only. Deactivate the account when a family leaves the CPE.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parents".
 */
export interface Parent {
  id: number;
  name: string;
  language: 'fr' | 'en';
  /**
   * The parent only sees content for these groups in the portal.
   */
  groups: (number | Group)[];
  active?: boolean | null;
  magicLinkExpiresAt?: string | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'parents';
}
/**
 * History of emails sent to parents. Created automatically — read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-log".
 */
export interface NotificationLog {
  id: number;
  title: string;
  sourceType: 'activity' | 'announcement' | 'campaign';
  sourceId: number;
  audience: string;
  recipients: number;
  delivered?: number | null;
  failed?: number | null;
  sentBy?: (number | null) | User;
  trigger?: ('manual' | 'schedule') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Help centre article categories (e.g. Registration, Fees, Meals). Order controls display in the portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-categories".
 */
export interface KbCategory {
  id: number;
  name: string;
  /**
   * A single emoji, e.g. 🍎
   */
  icon?: string | null;
  order?: number | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Official answers served by the parent portal assistant. Save as draft to preview, publish to make visible. Keywords improve search.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-articles".
 */
export interface KbArticle {
  id: number;
  question: string;
  /**
   * Rich text: bold, lists and links are preserved in the assistant.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  category: number | KbCategory;
  /**
   * Public: answers anonymous visitors on /faq and signed-in parents. Portal only: signed-in parents only.
   */
  audience: 'public' | 'portal';
  /**
   * Synonyms and variants parents might type (e.g. “fee”, “price”, “payment”).
   */
  keywords?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to temporarily hide the article without deleting it.
   */
  enabled?: boolean | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Emails to parents: draft → preview → send (immediate or scheduled). Every send is recorded in the notification log.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  /**
   * Visible to the team only (e.g. “Back-to-school reminder 2026”).
   */
  title: string;
  subject: string;
  /**
   * The message is wrapped in the CPE-branded template — use the preview.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  audience: 'all' | 'groups';
  groups?: (number | Group)[] | null;
  /**
   * Filled automatically when the campaign is created from an announcement.
   */
  relatedAnnouncement?: (number | null) | Announcement;
  /**
   * Leave empty for manual send. Scheduled sends go out on the scheduler’s next pass.
   */
  scheduledAt?: string | null;
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
  sentAt?: string | null;
  recipientsCount?: number | null;
  deliveredCount?: number | null;
  failedCount?: number | null;
  /**
   * Failed addresses, if any.
   */
  deliveryNote?: string | null;
  demoSeed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions asked to the assistant, scrubbed of personal information. Filter by “Refused” to spot content gaps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-log".
 */
export interface QuestionLog {
  id: number;
  question: string;
  locale: 'fr' | 'en';
  audience: 'public' | 'portal';
  outcome: 'answered' | 'refused' | 'gated';
  matchedArticles?: (number | KbArticle)[] | null;
  askedBy?: (number | null) | Parent;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'closure-dates';
        value: number | ClosureDate;
      } | null)
    | ({
        relationTo: 'faq-entries';
        value: number | FaqEntry;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'staff-profiles';
        value: number | StaffProfile;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'gallery-photos';
        value: number | GalleryPhoto;
      } | null)
    | ({
        relationTo: 'parents';
        value: number | Parent;
      } | null)
    | ({
        relationTo: 'notification-log';
        value: number | NotificationLog;
      } | null)
    | ({
        relationTo: 'kb-categories';
        value: number | KbCategory;
      } | null)
    | ({
        relationTo: 'kb-articles';
        value: number | KbArticle;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'question-log';
        value: number | QuestionLog;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'parents';
        value: number | Parent;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'parents';
        value: number | Parent;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  ageRange?: T;
  color?: T;
  order?: T;
  active?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  visibility?: T;
  image?: T;
  groups?: T;
  date?: T;
  endDate?: T;
  importantNote?: T;
  description?: T;
  checklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  eventDate?: T;
  body?: T;
  image?: T;
  videoUrl?: T;
  attachments?: T;
  scope?: T;
  groups?: T;
  pinned?: T;
  publishAt?: T;
  archived?: T;
  expiresAt?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closure-dates_select".
 */
export interface ClosureDatesSelect<T extends boolean = true> {
  label?: T;
  startDate?: T;
  endDate?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-entries_select".
 */
export interface FaqEntriesSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  audience?: T;
  order?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  audience?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-profiles_select".
 */
export interface StaffProfilesSelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  bio?: T;
  photo?: T;
  consent?: T;
  order?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  schedule?: T;
  description?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos_select".
 */
export interface GalleryPhotosSelect<T extends boolean = true> {
  caption?: T;
  takenAt?: T;
  activity?: T;
  consentConfirmed?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parents_select".
 */
export interface ParentsSelect<T extends boolean = true> {
  name?: T;
  language?: T;
  groups?: T;
  active?: T;
  magicLinkExpiresAt?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-log_select".
 */
export interface NotificationLogSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  sourceId?: T;
  audience?: T;
  recipients?: T;
  delivered?: T;
  failed?: T;
  sentBy?: T;
  trigger?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-categories_select".
 */
export interface KbCategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  order?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-articles_select".
 */
export interface KbArticlesSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  image?: T;
  category?: T;
  audience?: T;
  keywords?:
    | T
    | {
        term?: T;
        id?: T;
      };
  enabled?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  body?: T;
  audience?: T;
  groups?: T;
  relatedAnnouncement?: T;
  scheduledAt?: T;
  status?: T;
  sentAt?: T;
  recipientsCount?: T;
  deliveredCount?: T;
  failedCount?: T;
  deliveryNote?: T;
  demoSeed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-log_select".
 */
export interface QuestionLogSelect<T extends boolean = true> {
  question?: T;
  locale?: T;
  audience?: T;
  outcome?: T;
  matchedArticles?: T;
  askedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The CPE’s official contact information, shown across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  cpeName: string;
  tagline?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  hours?: string | null;
  /**
   * e.g. “CPE licensed by the ministère de la Famille” — a trust signal.
   */
  permitNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * One short, warm sentence.
   */
  heroTitle: string;
  heroSubtitle?: string | null;
  introTitle?: string | null;
  introText?: string | null;
  highlights?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  intro?: string | null;
  pedagogy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  values?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  facilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life-page".
 */
export interface LifePage {
  id: number;
  intro?: string | null;
  /**
   * Generic, reassuring schedule — no details specific to one group.
   */
  dailySchedule?:
    | {
        time: string;
        moment: string;
        id?: string | null;
      }[]
    | null;
  meals?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  activities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-page".
 */
export interface AdmissionPage {
  id: number;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  laPlaceUrl?: string | null;
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perks?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  cpeName?: T;
  tagline?: T;
  phone?: T;
  email?: T;
  address?: T;
  hours?: T;
  permitNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  introTitle?: T;
  introText?: T;
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  intro?: T;
  pedagogy?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  facilities?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life-page_select".
 */
export interface LifePageSelect<T extends boolean = true> {
  intro?: T;
  dailySchedule?:
    | T
    | {
        time?: T;
        moment?: T;
        id?: T;
      };
  meals?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-page_select".
 */
export interface AdmissionPageSelect<T extends boolean = true> {
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  laPlaceUrl?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  intro?: T;
  perks?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}